#!/bin/sh

sh ./art/welcome.sh
read -p "Johnny-Five: Hello, "$(whoami)". Shall we continue? (yes/no) " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
  sh ./art/start.sh
  sh ./scripts/brew.sh
  sh ./scripts/terminal.sh
  sh ./scripts/finder.sh
  sh ./scripts/fonts.sh
  sh ./scripts/vscode.sh
else
  sh ./art/goodbye.sh
  exit 0
fi

# Setup for NVM alias
[[ -d ~/.nvm ]] || mkdir ~/.nvm